### ISSUE TITLE
Investigate CLI size difference between 2.x and 3.x

### ISSUE THREAD

**Issue by fbiville** [liquigraph/liquigraph#169]
It seems 3.x is almost as 4 times as small as 2.x CLI. Why?

**Comment by fpavageau** [comment]
Not a PR (yet?), but a contribution still: `2.x` can use Neo4j classes in embedded mode:
- Use the [`GraphDatabaseService`](https://github.com/liquigraph/liquigraph/blob/2.x/liquigraph-core/src/main/java/org/liquigraph/core/configuration/ConfigurationBuilder.java#L49) as the "datasource".
- The JDBC driver can return a [`Node`](https://github.com/liquigraph/liquigraph/blob/2.x/liquigraph-core/src/main/java/org/liquigraph/core/io/ChangelogGraphReader.java#L79).

Because of that, `liquigraph-core` depends on Neo4j, which depends on Scala, etc. Since the dependencies are shaded into the jar, the resulting artifact is large.

I guess it makes no sense for the CLI to support the embedded mode, so we could trim the shaded dependencies: the only direct dependencies are `GraphDatabaseService` and `Node`, so if these classes can be loaded, that will be enough. It might be tedious to do it manually, though: I'm going to explore if that's doable.

**Comment by fbiville** [comment]
Thanks
