### ISSUE TITLE
Parameterized query and read from data file

### ISSUE THREAD

**Issue by katadonutskuri** [liquigraph/liquigraph#439]
Hi

I took a look at the documentation website, and didn't see mentions of parameterized queries and being able to read from a data file. Is this supported (I assume not since it's not there in the docs)? The reading from data files is for updates that are like 10k+, which obviously a person can't manually add those query tags to the xml file.

Or is there a way to code it in Java and run it that way?

**Comment by fbiville** [comment]
Hello, Liquigraph is going to its End of Life, and is being replaced by https://github.com/liquibase/liquibase-neo4j, the Neo4j plugin for Liquibase.
Since it's a Liquibase plugin, it supports most of the main features, including Cypher file inclusion.

There is no support for parameterized queries in Liquigraph.

Liquibase supports [changelog properties](https://docs.liquibase.com/concepts/basic/changelog-property-substitution.html), so it _may_ work if you define the properties in an XML change set and that change set includes a Cypher file (I have not tested this).
